#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for hap/encoding
#
# IDENTIFICATION
#    src/backend/hap/encoding/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/hap/encoding
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	hap_encoding.o

include $(top_srcdir)/src/backend/common.mk
