#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for hap/state
#
# IDENTIFICATION
#    src/backend/hap/state/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/hap/state
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	hap_state.o

include $(top_srcdir)/src/backend/common.mk
