#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for hap/access
#
# IDENTIFICATION
#    src/backend/hap/access/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/hap/access
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	hap_handler.o

include $(top_srcdir)/src/backend/common.mk
