#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for hap/executor
#
# IDENTIFICATION
#    src/backend/hap/executor/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/hap/executor
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = hap_lw_executor.o \

include $(top_srcdir)/src/backend/common.mk
