#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for hap/catalog
#
# IDENTIFICATION
#    src/backend/hap/catalog/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/hap/catalog
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	hap_catalog.o \
	pg_hap.o \
	pg_hap_hidden_attribute_desc.o \
	pg_hap_encoded_attribute.o

include $(top_srcdir)/src/backend/common.mk
