#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for hap/partition
#
# IDENTIFICATION
#    src/backend/hap/partition/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/hap/partition
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	hap_partition_create_stmt.o \
	hap_partition_parse.o \
	hap_partition_key.o \
	hap_partition_map.o

include $(top_srcdir)/src/backend/common.mk
