#
# Makefile for the HAP module
#
# src/backend/hap/Makefile
#

subdir = src/backend/hap
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = access catalog state encoding planner reduction partition executor

include $(top_srcdir)/src/backend/common.mk
